"""olf_kit.py -- EVERYTHING in one file: core builders + tables/images/animation/links +
SVG helpers + validator. Standard library only.

GENERATED by concatenating, in order: olf_starter.py, olf_starter_extras.py,
olf_starter_svg.py, olf_validate.py (do not edit; edit those and regenerate).

Use: attach THIS ONE FILE to the chat (or fetch it), then in your code sandbox:
    exec(open("olf_kit.py").read())        # or: from olf_kit import *
then build with Doc/Page (see spec/starter-helpers.md) and finish with
    print_report(validate_olf("out.olf"))
"""

# ==========================================================================
# ---- olf_starter.py
# ==========================================================================

"""olf_starter.py -- CORE helpers for building a myViewBoard .olf in a plain sandbox.

Standard library only. Paste this whole file into your code sandbox unchanged
(do not retype it), then call it. Ported from the reference engine
(olf-dsl/olf_dsl/core.py); the mechanical rules are baked in so you cannot forget
them: px font sizes, RTF colour sync, 8-digit text fill / 6-digit shape fill,
the triple separator, `additional` entries, curve stroke-opacity, and
wrapped-height text flow.

Typical use:

    doc = Doc("Lesson on X")
    p = doc.page()
    p.title("The Water Cycle")                 # flows from the top
    p.text("Body sentence ...", size=28)       # y advances by REAL wrapped height
    a = p.ellipse(400, 700, 120, fill="#BAE6FD")
    p.curve((520, 700), (700, 600), (900, 700), arrow_end=True)
    doc.save("out.olf")

Tables / images / animation / links live in olf_starter_extras.py (paste it AFTER
this file). Then run olf_validate.py on the saved file before delivering.
"""
import json
import textwrap
import uuid
import zipfile
from datetime import datetime

W, H = 1920, 1080
MATRIX = "1,0,0,0,1,0,0,0,1"
MARGIN, GUTTER = 80, 40
_MSEP = "\u300e\u300e\u300e"          # THREE U+300E chars. Never change.


def uid():
    return str(uuid.uuid4())


# ---- measurement strings (triple separator) --------------------------------
def _show_angle(n):
    return _MSEP.join(["true,"] * n)


def _show_length(n):
    return _MSEP.join(["false"] + ["true,False,"] * n)


POLY_LEN, POLY_ANG = _show_length(4), _show_angle(4)
LINE_LEN, ELLIPSE_LEN = _show_length(1), _show_length(2)


# ---- colour / font helpers --------------------------------------------------
def argb(c6):
    """'#RRGGBB' -> '#FFRRGGBB'. Text `fill` ONLY. Shapes stay 6-digit."""
    return "#FF" + c6.lstrip("#").upper()


def _rgb(c6):
    c = c6.lstrip("#")
    return int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16)


def json_font_size(pt):
    """JSON font-size is PIXELS = round(pt * 4/3). RTF keeps points (fs = pt*2)."""
    return float(round(pt * 4.0 / 3.0))


def _rtf_escape(v):
    """Escape for the RTF stream. Backslash and braces; non-ASCII as signed-16-bit
    \\uN? (what myViewBoard itself writes); and the literal word 'Arial', which
    myViewBoard silently rewrites to 'Calibri' in the decoded text, is broken with an
    invisible word-joiner (U+2060) so it displays correctly."""
    out = []
    for ch in v.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}"):
        o = ord(ch)
        if o < 128:
            out.append(ch)
        elif o <= 0xFFFF:
            out.append("\\u%d?" % (o - 0x10000 if o > 0x7FFF else o))
        else:                                   # astral: UTF-16 surrogate pair
            o -= 0x10000
            for s in (0xD800 + (o >> 10), 0xDC00 + (o & 0x3FF)):
                out.append("\\u%d?" % (s - 0x10000))
    return "".join(out).replace("Arial", "Ari\\u8288?al")


def make_rtf(value, pt, font="Segoe UI", align="left", bold=False, color="#000000"):
    r, g, b = _rgb(color)
    a = {"left": "\\ql", "center": "\\qc", "right": "\\qr", "justify": "\\qj"}.get(align, "\\ql")
    return (
        "{\\rtf1\\fbidis\\ansi\\ansicpg1252\\deff0\\nouicompat\\deflang1033"
        "{\\fonttbl{\\f0\\fnil\\fcharset0 " + font + ";}}\r\n"
        "{\\colortbl ;\\red%d\\green%d\\blue%d;}\r\n" % (r, g, b) +
        "{\\*\\generator Riched20 10.0.26100}\\viewkind4\\uc1 \r\n"
        "\\pard" + a + "\\tx720\\cf1" + ("\\b" if bold else "") +
        "\\f0\\fs" + str(int(pt * 2)) + " " + _rtf_escape(value) + "\\par\r\n}\r\n"
    )


# ---- text height estimate (no font metrics available -> be conservative) ----
# Wrapped-line pitch = (pitch ratio) x font size in POINTS. Measured on real renders at
# fs=44: Segoe UI 1.773, Calibri 1.614, Georgia 1.523, Open Sans 1.818, Times New
# Roman 1.477 (derived 1.533). The values below are those rounded UP. Bold is NOT
# different (same pitch as regular); only its glyphs are wider, handled in the line count.
PITCH = {"Segoe UI": 1.80, "Calibri": 1.65, "Georgia": 1.55, "Open Sans": 1.85,
         "Times New Roman": 1.55}
PITCH_DEFAULT = 1.85            # unknown / other families: generous


def pitch_ratio(font="Segoe UI"):
    return PITCH.get(font, PITCH_DEFAULT)


def estimate_lines(text, pt, width_px, bold=False):
    json_px = round(pt * 4 / 3)
    avg = json_px * (0.60 if bold else 0.55)    # deliberately generous; bold is wider
    per_line = max(1, int(width_px / avg))
    total = 0
    for para in str(text).split("\n"):
        total += max(1, len(textwrap.wrap(para, width=per_line, break_long_words=True)))
    return total


def estimate_height(text, pt, width_px, bold=False, font="Segoe UI"):
    """lines * pitch. NEVER use the pitch alone as a height."""
    return estimate_lines(text, pt, width_px, bold) * pt * pitch_ratio(font)


def badge_y(y_shape, shape_h, pt):
    """Textarea y that makes a SINGLE line of text look vertically centred inside a
    shape (calibrated against real renders). The textarea box is not the visual text
    box, so y = shape_centre - h/2 sits visibly too low/high; use this instead.
    Give the textarea the shape's full width and align='center'."""
    fs_c = max(20, min(64, pt))
    c = 0.40 + (fs_c - 20) / 44.0 * 0.16
    return y_shape + round(shape_h / 2 - c * pt)


# ---- elements ---------------------------------------------------------------
def textarea(x, y, w, h, text, pt, font="Segoe UI", bold=False, color="#1A1A2E",
             align="left"):
    fs = json_font_size(pt)
    ja = align if align in ("center", "right", "justify") else "left"
    return {"textarea": {
        "id": uid(), "x": float(x), "y": float(y), "width": float(w), "height": float(h),
        "custom-data": make_rtf(text, pt, font, align, bold, color),
        "custom-data-tag": "RTFxamlStr_UWP", "matrix": MATRIX,
        "text-blocks-container": [{"paragraph": {
            "id": uid(), "font-size": fs, "text-align": ja,
            "text-list-container": [{"text": {
                "id": uid(), "text": text, "font-family": font, "font-size": fs,
                "fill": argb(color), "font-style": "normal", "font-stretch": "normal",
                "font-weight": "bold" if bold else "normal",
                "text-decoration": "normal", "baseline-align": "baseline",
                "fill-opacity": 1.0}}]}}],
    }}


def _add(ref):
    return {"element": {"id": uid(), "ref": ref, "flip": "none", "is-locked": False,
                        "is-moveable-locked": False, "is-replicate": False}}


def polygon(points, fill="#FFFFFF", stroke=None, stroke_width=0.0):
    pid = uid()
    xs, ys = [p[0] for p in points], [p[1] for p in points]
    return {"polygon": {
        "id": pid, "x": 0.0, "y": 0.0,
        "width": float(max(xs) - min(xs)), "height": float(max(ys) - min(ys)),
        "matrix": MATRIX, "fill": fill, "stroke": stroke or fill,
        "stroke-width": float(stroke_width), "fill-opacity": 1.0,
        "stroke-opacity": 1.0 if stroke_width else 0.0,
        "is-show-incircle": False, "is-show-outcircle": False,
        "show-length-measurement": POLY_LEN, "show-angle-measurement": POLY_ANG,
        "points": " ".join("%s,%s" % (round(x, 3), round(y, 3)) for x, y in points),
    }}, _add(pid)


def rect(x, y, w, h, **kw):
    return polygon([(x, y), (x + w, y), (x + w, y + h), (x, y + h)], **kw)


def ellipse(cx, cy, rx, ry=None, fill="#FFFFFF", stroke="#000000", stroke_width=3.0):
    ry = rx if ry is None else ry
    eid, tx, ty, half = uid(), cx - rx, cy - ry, stroke_width / 2
    return {"ellipse": {
        "id": eid, "is-pie": False, "x": 0.0, "y": 0.0,
        "width": float(rx * 2 + stroke_width), "height": float(ry * 2 + stroke_width),
        "rx": float(rx), "ry": float(ry), "cx": float(rx), "cy": float(ry),
        "angle-start": 0.0, "angle-end": 359.9, "fill": fill, "stroke": stroke,
        "stroke-width": float(stroke_width), "fill-opacity": 1.0, "stroke-opacity": 1.0,
        "show-length-measurement": ELLIPSE_LEN, "show-angle-measurement": "",
        "matrix": "1,0,%s,0,1,%s,0,0,1" % (tx, ty),
        "boundary": "%s %s %s %s" % (tx - half, ty - half, tx + 2 * rx + half, ty + 2 * ry + half),
    }}, _add(eid)


def polyline(points, color="#CBD5E1", width=4.0, arrow_start=False, arrow_end=False,
             dashed=False):
    pid = uid()
    xs, ys = [p[0] for p in points], [p[1] for p in points]
    el = {"polyline": {
        "id": pid, "x": 0.0, "y": 0.0,
        "width": float(max(max(xs) - min(xs), 1)), "height": float(max(max(ys) - min(ys), 1)),
        "stroke-opacity": 1.0, "stroke-width": float(width), "stroke": color,
        "lineshape-start": "arrow" if arrow_start else "normal",
        "lineshape-end": "arrow" if arrow_end else "normal",
        "stroke-linecap": "round", "matrix": MATRIX, "show-length-measurement": LINE_LEN,
        "points": " ".join("%s,%s" % (round(x, 3), round(y, 3)) for x, y in points),
    }}
    if dashed:
        el["polyline"]["stroke-dasharray"] = "18,12"
    return el, _add(pid)


def curve(p_start, p_via, p_end, color="#000000", width=6.0, arrow_start=False,
          arrow_end=False):
    """Points absolute. Stored relative to bbox origin offset by stroke/2.
    stroke-opacity MUST be explicit 1.0 or the curve is invisible."""
    cid, half = uid(), width / 2
    pts = [p_start, p_via, p_end]
    x0, y0 = min(p[0] for p in pts) - half, min(p[1] for p in pts) - half
    rel = [(p[0] - x0, p[1] - y0) for p in pts]
    f = lambda q: "%s,%s" % (round(q[0], 4), round(q[1], 4))
    return {"curve": {
        "id": cid, "x": float(x0), "y": float(y0),
        "width": float(max(p[0] for p in pts) - min(p[0] for p in pts) + width),
        "height": float(max(p[1] for p in pts) - min(p[1] for p in pts) + width),
        "stroke-width": float(width), "stroke-opacity": 1.0,
        "stroke-linecap-start": "arrow" if arrow_start else "round",
        "stroke-linecap-end": "arrow" if arrow_end else "round",
        "start-point": f(rel[0]), "second-point": f(rel[1]), "end-point": f(rel[2]),
        "stroke": color, "matrix": MATRIX,
    }}, _add(cid)


# ---- page / document --------------------------------------------------------
class Page:
    """Collects elements; `y` is the auto-flow cursor for title()/text()."""

    def __init__(self, doc, bg="#FFFFFF"):
        self.doc, self.bg, self.elements, self.y = doc, bg, [], MARGIN

    def add(self, built):
        """Accepts an element, or (element, additional_entry). Returns element id."""
        el, add = built if isinstance(built, tuple) else (built, None)
        self.elements.append(el)
        if add is not None:
            self.doc.additional.append(add)
        return next(iter(el.values()))["id"]

    # flowing text: height = lines * pitch; next y = y + height + GUTTER
    def text(self, text, size=28, x=MARGIN, width=W - 2 * MARGIN, bold=False,
             color="#1A1A2E", align="left", y=None, gap=GUTTER, font="Segoe UI"):
        top = self.y if y is None else y
        h = estimate_height(text, size, width, bold=bold, font=font)
        tid = self.add(textarea(x, top, width, h, text, size, font=font, bold=bold,
                                color=color, align=align))
        if y is None:
            self.y = top + h + gap
        return tid

    def title(self, text, size=44, **kw):
        kw.setdefault("bold", True)
        return self.text(text, size=size, **kw)

    def bullets(self, items, size=28, x=MARGIN, width=W - 2 * MARGIN - 60, marker="\u2022"):
        """Simple flowing list: one textarea per item, text prefixed with a marker.
        (The engine's compound bullets element is richer; see elements/bullets.md.)"""
        return [self.text("%s  %s" % (marker, it), size=size, x=x, width=width, gap=20)
                for it in items]

    def rect(self, *a, **k): return self.add(rect(*a, **k))
    def ellipse(self, *a, **k): return self.add(ellipse(*a, **k))
    def polyline(self, *a, **k): return self.add(polyline(*a, **k))
    def curve(self, *a, **k): return self.add(curve(*a, **k))


class Doc:
    def __init__(self, description="Generated OLF"):
        self.description, self.pages, self.additional = description, [], []
        self.links, self.extra_files = [], {}

    def page(self, bg="#FFFFFF"):
        p = Page(self, bg)
        self.pages.append(p)
        return p

    def content(self):
        now = datetime.now().strftime("%m/%d/%Y %I:%M:%S %p").lstrip("0").replace("/0", "/")
        pageset = [{"page": {
            "id": uid(), "matrix": MATRIX, "viewbox": "0,0,1920,1080",   # commas
            "is-hidden": False, "elements": p.elements,
            "backgrounds": [{"background": {"id": uid(), "type": "color",
                                            "fill": p.bg, "opacity": 1.0}}],
        }} for p in self.pages]
        return {"olf": {
            "width": 1920.0, "height": 1080.0, "viewbox": "0 0 1920 1080",   # spaces
            "meta": {
                "id": uid(), "create-platform": "myViewBoard for Windows",
                "create-by-library": "Viewsonic Open Learning Format library",
                "create-time": now, "modify-time": now,
                "create-library-version": "0.0.1.50",
                "create-version": "3.4.9.603 [64 bits]",
                "modify-version": "3.4.9.603 [64 bits]",
                "modify-platform": "myViewBoard for Windows",
                "description": self.description},
            "pageset": pageset, "additional": self.additional,
            "links": self.links, "groups": [],
        }}

    def save(self, path):
        """content.json must sit at the ZIP ROOT. ensure_ascii=False keeps U+300E raw."""
        with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("content.json", json.dumps(self.content(), ensure_ascii=False))
            for arc, data in self.extra_files.items():
                zf.writestr(arc, data)
        return path

# ==========================================================================
# ---- olf_starter_extras.py
# ==========================================================================

"""olf_starter_extras.py -- tables, images, animation, links.

Paste AFTER olf_starter.py (it uses uid, MATRIX, _add, textarea, estimate_height,
Page, Doc from there). Standard library only. Ported from olf-dsl core.py.

    t = add_table(p, x=80, y=p.y, col_lengths=[400, 800], row_lengths=[70, 70, 70],
                  cells=[["Stage", "What happens"], ["Evaporation", "Water -> vapor"],
                         ["Condensation", "Vapor -> clouds"]])
    p.y = t["bottom"] + GUTTER
    animate(doc, some_element_id, "fade-in", "2")
    link_page(doc, some_element_id, 3)         # jumps to page 3 (1-based)
"""

TABLE_PAD = 18.0                 # cell text inset from the cell interior, both axes
CELL_BG, CELL_BG_OPACITY = "#FFFFFF", 0.2


def _table_shell(x, y, col_lengths, row_lengths, stroke="#000000", sw=3.0):
    tid, cols, rows = uid(), len(col_lengths), len(row_lengths)
    bgs = [{"cell-background": {"id": uid(), "background": CELL_BG,
                                "background-opacity": CELL_BG_OPACITY,
                                "cell-column": c, "cell-row": r}}   # DENSE, column-major
           for c in range(cols) for r in range(rows)]
    return {"table": {
        "id": tid, "x": float(x), "y": float(y),
        "width": float(sum(col_lengths) + (cols + 1) * sw),
        "height": float(sum(row_lengths) + (rows + 1) * sw),
        "rows": rows, "columns": cols, "matrix": MATRIX,
        "stroke": stroke, "stroke-width": float(sw), "stroke-opacity": 1.0,
        "column-lengths-array": " ".join(str(v) for v in col_lengths),
        "row-lengths-array": " ".join(str(v) for v in row_lengths),
        "column-min-lengths-array": " ".join(["1"] * cols),
        "row-min-lengths-array": " ".join(["1"] * rows),
        "cell-background-container": bgs,
        "merge-cell-container": [], "cell-content-container": [],
    }}, _add(tid)


def _merge_entries(rows, cols, merges):
    """merges = [(row, col, row_span, col_span)] in plain 0-based CELL counts.
    One entry per cell, COLUMN-major; EVEN index space; extent = 2k-1."""
    anchors, swallowed = {}, {}
    for r, c, kr, kc in merges:
        anchors[(r, c)] = (2 * kr - 1, 2 * kc - 1)
        for dr in range(kr):
            for dc in range(kc):
                if (dr, dc) != (0, 0):
                    swallowed[(r + dr, c + dc)] = (r, c)
    out = []
    for c in range(cols):
        for r in range(rows):
            if (r, c) in anchors:
                out.append(("%d,%d" % (2 * r, 2 * c),) + anchors[(r, c)])
            elif (r, c) in swallowed:
                ar, ac = swallowed[(r, c)]
                out.append(("%d,%d" % (2 * ar, 2 * ac), 1, 1))
            else:
                out.append(("-1,-1", 1, 1))
    return out, swallowed


def add_table(page, x, y, col_lengths, row_lengths, cells, size=22, header=True,
              merges=(), sw=3.0):
    """cells[r][c] = text or None. Creates the table AND one textarea per cell,
    registers cell-content in the EVEN index space. Returns {'id','bottom'}.
    Cell width for wrap estimation = column length - 2*TABLE_PAD."""
    shell, add = _table_shell(x, y, col_lengths, row_lengths, sw=sw)
    t = shell["table"]
    rows, cols = len(row_lengths), len(col_lengths)
    if merges:
        entries, swallowed = _merge_entries(rows, cols, merges)
        t["merge-cell-container"] = [{"merge-cell": {
            "id": uid(), "start-from": sf, "merge-cell-rows": mr, "merge-cell-columns": mc}}
            for sf, mr, mc in entries]
    else:
        swallowed = {}
    page.add((shell, add))
    for r in range(rows):
        for c in range(cols):
            txt = cells[r][c] if r < len(cells) and c < len(cells[r]) else None
            if not txt:
                continue
            ix = x + sw + sum(v + sw for v in col_lengths[:c]) + TABLE_PAD
            iy = y + sw + sum(v + sw for v in row_lengths[:r]) + TABLE_PAD
            w = col_lengths[c] - 2 * TABLE_PAD
            bold = header and r == 0
            h = estimate_height(txt, size, w, bold=bold)
            ta = textarea(ix, iy, w, h, txt, size, bold=bold)
            page.elements.append(ta)
            rr, cc = swallowed.get((r, c), (r, c))
            t["cell-content-container"].append({"cell-content": {
                "id": uid(), "cell-row": 2 * rr, "cell-column": 2 * cc,
                "ref": ta["textarea"]["id"]}})
            # Row too short for wrapped text? Warn -- enlarge row_lengths instead.
            if h + 2 * TABLE_PAD > row_lengths[r] and (r, c) not in swallowed:
                print("WARNING: cell (%d,%d) needs ~%d tall, row is %s -- raise row_lengths"
                      % (r, c, h + 2 * TABLE_PAD, row_lengths[r]))
    return {"id": t["id"], "bottom": y + t["height"]}


def add_image(page, doc, arcname, data, mime, x, y, w, h):
    """arcname like 'images/pic.png'; data = bytes. Image elements need NO additional entry."""
    doc.extra_files[arcname] = data
    return page.add({"image": {"id": uid(), "x": float(x), "y": float(y),
                               "width": float(w), "height": float(h),
                               "mime-type": mime, "source": arcname, "matrix": MATRIX}})


def animate(doc, ref_id, anim_type="fade-in", duration="2"):
    """Attach to an element's `additional` entry. anim_type fade-in|fade-out;
    duration is a STRING '0'..'3'. Both types on one element = tap toggles it."""
    for a in doc.additional:
        if a["element"]["ref"] == ref_id:
            a["element"].setdefault("animation-container", []).append(
                {"animation": {"id": uid(), "type": anim_type, "duration": str(duration)}})
            return
    # image/textarea elements have no entry yet: create one WITHOUT flip is wrong for
    # shapes, but these types have none, so build the minimal entry.
    doc.additional.append({"element": {
        "id": uid(), "ref": ref_id, "is-locked": False, "is-moveable-locked": False,
        "is-replicate": False,
        "animation-container": [{"animation": {"id": uid(), "type": anim_type,
                                               "duration": str(duration)}}]}})


def _link(doc, ref_id, link_type, payload):
    entry = {"id": uid(), "ref": ref_id, "link-type": link_type}
    entry.update(payload)
    doc.links.append({"link": entry})


def link_page(doc, ref_id, page_number):
    """page-id is the 1-BASED ORDINAL as a STRING, never a page UUID."""
    _link(doc, ref_id, "page", {"page-id": str(int(page_number))})


def link_web(doc, ref_id, url):
    _link(doc, ref_id, "web", {"url": url})

# ==========================================================================
# ---- olf_starter_svg.py
# ==========================================================================

"""olf_starter_svg.py -- SVG support: AI-pen vector icons/shapes and SVG image elements.

Paste AFTER olf_starter.py (uses uid, MATRIX, Page, Doc). Standard library only.
Does NOT need olf_starter_extras.py.

Two ways to put SVG on a canvas (see elements/svg-image.md and elements/ai-pen.md):

  A. TRUE VECTOR (scales cleanly): turn SVG path data into an AI-pen element.
        p.add(ai_pen_icon(["M10 20v-6h4v6h5v-8h3L12 3L2 12h3v8z"], x=340, y=440,
                          size=200, vb=24, fill="#1565C0"))
        # or straight from SVG text:
        paths, (vw, vh), warns = svg_to_paths(svg_text)
        p.add(ai_pen_icon(paths, x=100, y=100, size=200, vb=max(vw, vh)))
        p.add(ai_pen_rounded_rect(80, 80, 600, 300, 40, "#E0F2FE"))

  B. RASTERISED SVG IMAGE (any look, but pixelates if scaled up): an `image`
     element with mime image/svg+xml. Author it big; this helper does that:
        add_svg_image(p, doc, "diagram", svg_text, x=560, y=250, w=800, h=530)

Both are linted: unsupported SVG features are reported as warnings.
"""
import math
import re
import xml.etree.ElementTree as ET

_CMD = re.compile(r"\s*([MmLlHhVvCcSsQqTtAaZz])")
_NUM = re.compile(r"\s*,?\s*([-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?)")
_FLAG = re.compile(r"\s*,?\s*([01])")
_MORE = re.compile(r"\s*,?\s*[-+.\d]")
_ARITY = {"M": 2, "L": 2, "H": 1, "V": 1, "C": 6, "S": 4, "Q": 4, "T": 2, "A": 7}


def _fmt(v):
    s = ("%.4f" % v).rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


# ---------------------------------------------------------------------------
# 1. Path parsing -> absolute M / L / C / A / Z only
# ---------------------------------------------------------------------------
def parse_path(d):
    """SVG path data -> list of absolute segments:
    ('M',x,y) ('L',x,y) ('C',x1,y1,x2,y2,x,y) ('A',rx,ry,rot,large,sweep,x,y) ('Z',)
    H/V -> L, Q/T -> exact cubic C, S -> C, relative -> absolute."""
    segs, i, n = [], 0, len(d)
    cx = cy = sx = sy = 0.0
    lc = lq = None                      # last cubic / quad control point
    cmd = None
    while True:
        m = _CMD.match(d, i)
        if m:
            cmd, i = m.group(1), m.end()
            if cmd in "Zz":
                segs.append(("Z",))
                cx, cy, lc, lq = sx, sy, None, None
                continue
        else:
            if re.compile(r"\s*,?\s*").match(d, i).end() >= n:
                break
            if cmd is None or cmd in "Zz":
                raise ValueError("bad path data near %r" % d[i:i + 12])
        rel, up = cmd.islower(), cmd.upper()
        first_set = True
        while first_set or _MORE.match(d, i):
            first_set = False
            args = []
            for k in range(_ARITY[up]):
                if up == "A" and k in (3, 4):
                    mm = _FLAG.match(d, i)
                else:
                    mm = _NUM.match(d, i)
                if not mm:
                    raise ValueError("missing number in path near %r" % d[i:i + 12])
                args.append(float(mm.group(1)))
                i = mm.end()
            ox, oy = (cx, cy) if rel else (0.0, 0.0)
            if up == "M":
                cx, cy = args[0] + ox, args[1] + oy
                sx, sy = cx, cy
                segs.append(("M", cx, cy))
                lc = lq = None
                up, rel = "L", rel       # implicit repeats are lineto
            elif up == "L":
                cx, cy = args[0] + ox, args[1] + oy
                segs.append(("L", cx, cy)); lc = lq = None
            elif up == "H":
                cx = args[0] + (cx if rel else 0.0)
                segs.append(("L", cx, cy)); lc = lq = None
            elif up == "V":
                cy = args[0] + (cy if rel else 0.0)
                segs.append(("L", cx, cy)); lc = lq = None
            elif up == "C":
                x1, y1, x2, y2, x, y = (args[0] + ox, args[1] + oy, args[2] + ox,
                                        args[3] + oy, args[4] + ox, args[5] + oy)
                segs.append(("C", x1, y1, x2, y2, x, y))
                lc, lq, cx, cy = (x2, y2), None, x, y
            elif up == "S":
                x1, y1 = (2 * cx - lc[0], 2 * cy - lc[1]) if lc else (cx, cy)
                x2, y2, x, y = args[0] + ox, args[1] + oy, args[2] + ox, args[3] + oy
                segs.append(("C", x1, y1, x2, y2, x, y))
                lc, lq, cx, cy = (x2, y2), None, x, y
            elif up in "QT":
                if up == "Q":
                    qx, qy, x, y = args[0] + ox, args[1] + oy, args[2] + ox, args[3] + oy
                else:
                    qx, qy = (2 * cx - lq[0], 2 * cy - lq[1]) if lq else (cx, cy)
                    x, y = args[0] + ox, args[1] + oy
                segs.append(("C", cx + 2 / 3 * (qx - cx), cy + 2 / 3 * (qy - cy),
                             x + 2 / 3 * (qx - x), y + 2 / 3 * (qy - y), x, y))
                lq, lc, cx, cy = (qx, qy), None, x, y
            elif up == "A":
                x, y = args[5] + ox, args[6] + oy
                segs.append(("A", abs(args[0]), abs(args[1]), args[2],
                             int(args[3]), int(args[4]), x, y))
                cx, cy, lc, lq = x, y, None, None
    return segs


def segs_to_d(segs, dx=0.0, dy=0.0):
    out = []
    for s in segs:
        k = s[0]
        if k == "Z":
            out.append("Z")
        elif k in "ML":
            out.append("%s%s %s" % (k, _fmt(s[1] + dx), _fmt(s[2] + dy)))
        elif k == "C":
            out.append("C%s %s %s %s %s %s" % (
                _fmt(s[1] + dx), _fmt(s[2] + dy), _fmt(s[3] + dx), _fmt(s[4] + dy),
                _fmt(s[5] + dx), _fmt(s[6] + dy)))
        else:  # A
            out.append("A%s %s %s %d %d %s %s" % (
                _fmt(s[1]), _fmt(s[2]), _fmt(s[3]), s[4], s[5], _fmt(s[6] + dx), _fmt(s[7] + dy)))
    return "".join(out)


# ---------------------------------------------------------------------------
# 2. Geometry helpers: arc sampling, flattening, bbox, hole-risk heuristic
# ---------------------------------------------------------------------------
def _arc_points(x1, y1, rx, ry, phi_deg, fa, fs, x2, y2, n=16):
    if rx == 0 or ry == 0 or (x1 == x2 and y1 == y2):
        return [(x2, y2)]
    phi = math.radians(phi_deg)
    cp, sp = math.cos(phi), math.sin(phi)
    dx, dy = (x1 - x2) / 2, (y1 - y2) / 2
    x1p, y1p = cp * dx + sp * dy, -sp * dx + cp * dy
    lam = (x1p ** 2) / (rx ** 2) + (y1p ** 2) / (ry ** 2)
    if lam > 1:
        s = math.sqrt(lam); rx, ry = rx * s, ry * s
    num = rx ** 2 * ry ** 2 - rx ** 2 * y1p ** 2 - ry ** 2 * x1p ** 2
    den = rx ** 2 * y1p ** 2 + ry ** 2 * x1p ** 2
    co = math.sqrt(max(0.0, num / den)) * (-1 if fa == fs else 1)
    cxp, cyp = co * rx * y1p / ry, -co * ry * x1p / rx
    cx = cp * cxp - sp * cyp + (x1 + x2) / 2
    cy = sp * cxp + cp * cyp + (y1 + y2) / 2
    ang = lambda ux, uy, vx, vy: math.atan2(ux * vy - uy * vx, ux * vx + uy * vy)
    t1 = ang(1, 0, (x1p - cxp) / rx, (y1p - cyp) / ry)
    dt = ang((x1p - cxp) / rx, (y1p - cyp) / ry, (-x1p - cxp) / rx, (-y1p - cyp) / ry)
    if not fs and dt > 0:
        dt -= 2 * math.pi
    elif fs and dt < 0:
        dt += 2 * math.pi
    pts = []
    for k in range(1, n + 1):
        t = t1 + dt * k / n
        pts.append((cp * rx * math.cos(t) - sp * ry * math.sin(t) + cx,
                    sp * rx * math.cos(t) + cp * ry * math.sin(t) + cy))
    return pts


def flatten(segs):
    """-> list of subpaths, each a list of (x, y) points (curves/arcs sampled)."""
    subs, cur, cx, cy = [], [], 0.0, 0.0
    for s in segs:
        k = s[0]
        if k == "M":
            if len(cur) > 1:
                subs.append(cur)
            cx, cy = s[1], s[2]; cur = [(cx, cy)]
        elif k == "L":
            cx, cy = s[1], s[2]; cur.append((cx, cy))
        elif k == "C":
            for t in [i / 10 for i in range(1, 11)]:
                u = 1 - t
                cur.append((u**3 * cx + 3 * u * u * t * s[1] + 3 * u * t * t * s[3] + t**3 * s[5],
                            u**3 * cy + 3 * u * u * t * s[2] + 3 * u * t * t * s[4] + t**3 * s[6]))
            cx, cy = s[5], s[6]
        elif k == "A":
            cur += _arc_points(cx, cy, s[1], s[2], s[3], s[4], s[5], s[6], s[7])
            cx, cy = s[6], s[7]
        elif k == "Z" and cur:
            cx, cy = cur[0]
    if len(cur) > 1:
        subs.append(cur)
    return subs


def bbox_of(segs):
    pts = [p for sub in flatten(segs) for p in sub]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    return min(xs), min(ys), max(xs), max(ys)


def _area(pts):
    return sum(pts[i][0] * pts[(i + 1) % len(pts)][1] - pts[(i + 1) % len(pts)][0] * pts[i][1]
               for i in range(len(pts))) / 2


def hole_risk(segs):
    """Heuristic WARNING for the 'opposite-winding donut hole' trap: a subpath whose
    bbox lies inside another subpath's bbox and winds the opposite way."""
    subs = [(p, _area(p)) for p in flatten(segs) if len(p) > 2]
    bb = [(min(q[0] for q in p), min(q[1] for q in p), max(q[0] for q in p), max(q[1] for q in p))
          for p, _ in subs]
    risks = 0
    for i in range(len(subs)):
        for j in range(len(subs)):
            if i != j and subs[i][1] * subs[j][1] < 0:
                a, b = bb[i], bb[j]
                if a[0] <= b[0] and a[1] <= b[1] and a[2] >= b[2] and a[3] >= b[3] \
                        and abs(subs[i][1]) > abs(subs[j][1]):
                    risks += 1
    return risks


# ---------------------------------------------------------------------------
# 3. AI-pen builders
# ---------------------------------------------------------------------------
_HEX6 = re.compile(r"^#[0-9A-Fa-f]{6}$")


def _hex6(c, default):
    """Only plain #RRGGBB is allowed in AI-pen fill/stroke (Android CRASHES otherwise)."""
    if isinstance(c, str):
        c = c.strip()
        if _HEX6.match(c):
            return c.upper()
        if re.match(r"^#[0-9A-Fa-f]{3}$", c):
            return "#" + "".join(ch * 2 for ch in c[1:]).upper()
    return default


def _ai_pen(items, matrix, w, h, stroke_color, stroke_width):
    """items = [(d, fill6)]. Foreground + MIRRORED background container (required:
    an AI-pen with an empty background container or identity matrix can render invisible)."""
    fg, bg = [], []
    for d, fill in items:
        stroke = stroke_color or fill
        p = {"id": uid(), "x": 0.0, "y": 0.0, "width": float(w), "height": float(h),
             "fill-opacity": 1.0, "fill": fill, "stroke-width": float(stroke_width),
             "stroke-opacity": 1.0 if stroke_width > 0 else 0.0,
             "stroke-miter-limit": 10.0, "lineshape-start": "round",
             "lineshape-end": "round", "lineshape-join": "round",
             "stroke": stroke, "data": d, "matrix": matrix}
        q = dict(p); q["id"] = uid(); q["fill-opacity"] = 0.3
        q["stroke-width"] = 0.5; q["stroke-opacity"] = 0.3 if stroke_width > 0 else 0.0
        fg.append({"path": p}); bg.append({"path": q})
    pid = uid()
    elem = {"AI-pen": {"id": pid, "matrix": matrix,
                       "foreground-objects-container": fg,
                       "background-objects-container": bg}}
    # AI-pen `additional` entry has NO "flip" field.
    add = {"element": {"id": uid(), "ref": pid, "is-locked": False,
                       "is-moveable-locked": False, "is-replicate": False}}
    return elem, add


def ai_pen_icon(paths, x, y, size, vb=24.0, fill="#1565C0", stroke_color=None,
                stroke_width=0.0):
    """Place SVG path data on the canvas as a true-vector AI-pen shape.

    paths : list of `d` strings, or (d, "#RRGGBB") tuples for per-path colours
    x, y  : canvas top-left of the icon box;  size : displayed px (square box)
    vb    : the icon's own viewBox size (24 for Material/MDI, 256 Phosphor, 16 Bootstrap)
    Paths are scrubbed to absolute M/L/C/A/Z and kept non-negative (offset folded
    into the matrix). Solid fill only: gradients / currentColor / names are replaced
    with `fill`.  Returns (element, additional_entry) -- feed to page.add()."""
    items, all_segs = [], []
    for it in paths:
        d, f = (it, None) if isinstance(it, str) else it
        segs = parse_path(d)
        all_segs.append(segs)
        items.append((segs, _hex6(f, _hex6(fill, "#1565C0"))))
    mins_x = min(bbox_of(s)[0] for s in all_segs)
    mins_y = min(bbox_of(s)[1] for s in all_segs)
    sx_ = -mins_x if mins_x < 0 else 0.0
    sy_ = -mins_y if mins_y < 0 else 0.0
    maxx = max(bbox_of(s)[2] for s in all_segs) + sx_
    maxy = max(bbox_of(s)[3] for s in all_segs) + sy_
    scale = float(size) / float(vb)
    tx, ty = x - sx_ * scale, y - sy_ * scale
    matrix = "%s,0,%s,0,%s,%s,0,0,1" % (_fmt(scale), _fmt(tx), _fmt(scale), _fmt(ty))
    ready = [(segs_to_d(s, sx_, sy_), f) for s, f in items]
    return _ai_pen(ready, matrix, max(vb, maxx), max(vb, maxy),
                   _hex6(stroke_color, None), stroke_width)


def ai_pen_rounded_rect(x, y, w, h, r, fill, stroke=None, stroke_width=0.0):
    """Rounded-rectangle card. Identical to the reference engine's make_rounded_rect.
    Keep stroke_width=0 (strokes render thicker on the curved corners)."""
    r = float(max(0.0, min(r, min(w, h) / 2.0)))
    lw, lh = float(w), float(h)
    if r <= 0:
        d = "M0.0,0.0 L%s,0.0 L%s,%s L0.0,%s Z" % (lw, lw, lh, lh)
    else:
        d = ("M%s,0.0 L%s,0.0 A%s,%s 0 0 1 %s,%s L%s,%s A%s,%s 0 0 1 %s,%s "
             "L%s,%s A%s,%s 0 0 1 0.0,%s L0.0,%s A%s,%s 0 0 1 %s,0.0 Z" % (
                 r, lw - r, r, r, lw, r, lw, lh - r, r, r, lw - r, lh,
                 r, lh, r, r, lh - r, r, r, r, r))
    matrix = "1,0,%s,0,1,%s,0,0,1" % (x, y)
    return _ai_pen([(d, fill)], matrix, lw, lh, stroke, stroke_width)


# ---------------------------------------------------------------------------
# 4. SVG text -> paths  (+ lint)
# ---------------------------------------------------------------------------
def _local(tag):
    return tag.split("}")[-1]


def _ellipse_d(cx, cy, rx, ry):
    return "M%s %sA%s %s 0 1 0 %s %sA%s %s 0 1 0 %s %sZ" % (
        _fmt(cx - rx), _fmt(cy), _fmt(rx), _fmt(ry), _fmt(cx + rx), _fmt(cy),
        _fmt(rx), _fmt(ry), _fmt(cx - rx), _fmt(cy))


def _rect_d(x, y, w, h, rx, ry):
    rx, ry = min(rx or ry or 0, w / 2), min(ry or rx or 0, h / 2)
    if rx <= 0 or ry <= 0:
        return "M%s %sL%s %sL%s %sL%s %sZ" % (_fmt(x), _fmt(y), _fmt(x + w), _fmt(y),
                                               _fmt(x + w), _fmt(y + h), _fmt(x), _fmt(y + h))
    return ("M%s %sL%s %sA%s %s 0 0 1 %s %sL%s %sA%s %s 0 0 1 %s %sL%s %sA%s %s 0 0 1 %s %s"
            "L%s %sA%s %s 0 0 1 %s %sZ" % (
                _fmt(x + rx), _fmt(y), _fmt(x + w - rx), _fmt(y), _fmt(rx), _fmt(ry),
                _fmt(x + w), _fmt(y + ry), _fmt(x + w), _fmt(y + h - ry), _fmt(rx), _fmt(ry),
                _fmt(x + w - rx), _fmt(y + h), _fmt(x + rx), _fmt(y + h), _fmt(rx), _fmt(ry),
                _fmt(x), _fmt(y + h - ry), _fmt(x), _fmt(y + ry), _fmt(rx), _fmt(ry),
                _fmt(x + rx), _fmt(y)))


def svg_to_paths(svg_text):
    """Extract fillable shapes from SVG text -> ([(d, '#RRGGBB'|None)], (vw, vh), warnings).
    Handles path, circle, ellipse, rect (incl. rounded), polygon, polyline.
    Ignores (with a warning): transforms, strokes-only shapes, gradients, text, use."""
    warns = []
    root = ET.fromstring(svg_text)
    vb = root.get("viewBox")
    if vb:
        parts = [float(v) for v in re.split(r"[ ,]+", vb.strip())]
        vw, vh = parts[2], parts[3]
        if parts[0] or parts[1]:
            warns.append("viewBox origin is not 0,0 -- shapes may need shifting")
    else:
        num = lambda s: float(re.sub(r"[a-z%]+$", "", s or "24"))
        vw, vh = num(root.get("width")), num(root.get("height"))
    out = []
    num = lambda e, k, dflt=0.0: float(re.sub(r"[a-z%]+$", "", e.get(k) or str(dflt)))
    for el in root.iter():
        t = _local(el.tag)
        if t in ("text", "use", "symbol", "mask", "pattern", "foreignObject", "image"):
            warns.append("<%s> is not converted (unsupported)" % t)
        if t in ("linearGradient", "radialGradient"):
            warns.append("gradients are not supported in AI-pen -- solid fill used")
        if el.get("transform"):
            warns.append("transform=%r on <%s> ignored -- bake transforms into coordinates" % (el.get("transform"), t))
        d = None
        if t == "path":
            d = el.get("d")
        elif t == "circle":
            d = _ellipse_d(num(el, "cx"), num(el, "cy"), num(el, "r"), num(el, "r"))
        elif t == "ellipse":
            d = _ellipse_d(num(el, "cx"), num(el, "cy"), num(el, "rx"), num(el, "ry"))
        elif t == "rect":
            d = _rect_d(num(el, "x"), num(el, "y"), num(el, "width"), num(el, "height"),
                        num(el, "rx"), num(el, "ry"))
        elif t in ("polygon", "polyline"):
            nums = [float(v) for v in re.findall(r"[-+]?\d*\.?\d+", el.get("points", ""))]
            pts = list(zip(nums[0::2], nums[1::2]))
            if pts:
                d = "M" + "L".join("%s %s" % (_fmt(a), _fmt(b)) for a, b in pts) + "Z"
        elif t == "line":
            warns.append("<line> has no fill -- not converted (use a thin rect instead)")
        if not d:
            continue
        fillv = el.get("fill")
        if (fillv or "").strip().lower() == "none":
            warns.append("<%s> has fill=none (stroke-only) -- skipped; AI-pen icons are fill-based" % t)
            continue
        f = _hex6(fillv, None)
        if fillv and f is None and fillv != "currentColor":
            warns.append("fill %r is not plain hex -- default fill used" % fillv)
        out.append((d, f))
    return out, (vw, vh), warns


_BAD = [("pattern", "<pattern> fills render SOLID BLACK -- do not use"),
        ("mask", "<mask> is ignored (flat opaque) -- use clipPath or pre-render"),
        ("text", "<text> renders NOTHING -- convert text to paths (AI-pen glyph outlines)"),
        ("use", "<use> does not resolve -- inline the geometry"),
        ("symbol", "<symbol> does not resolve -- inline the geometry"),
        ("foreignObject", "<foreignObject> content is silently dropped"),
        ("animate", "SMIL animation never plays (static render)"),
        ("animateTransform", "SMIL animation never plays (static render)"),
        ("set", "SMIL animation never plays (static render)")]


def svg_lint(svg_text, display_w=None):
    """Warnings for features that fail inside an `image`-element SVG."""
    w = []
    try:
        root = ET.fromstring(svg_text)
    except ET.ParseError as e:
        return ["SVG is not well-formed XML: %s" % e]
    seen = set()
    for el in root.iter():
        t = _local(el.tag)
        for tag, msg in _BAD:
            if t == tag and tag not in seen:
                seen.add(tag); w.append(msg)
        href = el.get("{http://www.w3.org/1999/xlink}href") or el.get("href")
        if href and href.startswith("http"):
            w.append("external resource %s will not load" % href[:40])
    if "@keyframes" in svg_text or "animation:" in svg_text:
        w.append("CSS animation never plays (static render)")
    if display_w:
        wid = root.get("width")
        if wid and re.match(r"^[\d.]+(px)?$", wid) and float(re.sub("px", "", wid)) < display_w * 4:
            w.append("intrinsic width %s < 4x display width %s -- will look blurry; author ~8x" % (wid, display_w))
    return w


def _set_svg_size(svg_text, w, h):
    m = re.search(r"<svg\b[^>]*>", svg_text)
    tag = m.group(0)
    new = tag
    if "viewBox" not in tag:
        ow = re.search(r'\bwidth="([\d.]+)', tag); oh = re.search(r'\bheight="([\d.]+)', tag)
        if ow and oh:
            new = new.replace("<svg", '<svg viewBox="0 0 %s %s"' % (ow.group(1), oh.group(1)), 1)
    for attr, val in (("width", w), ("height", h)):
        if re.search(r'\b%s="[^"]*"' % attr, new):
            new = re.sub(r'\b%s="[^"]*"' % attr, '%s="%d"' % (attr, val), new, 1)
        else:
            new = new.replace("<svg", '<svg %s="%d"' % (attr, val), 1)
    return svg_text.replace(tag, new, 1)


def add_svg_image(page, doc, name, svg_text, x, y, w, h, oversample=8):
    """`image` element with mime image/svg+xml. Rewrites the SVG root width/height to
    oversample x the display size (myViewBoard rasterises at intrinsic size, so
    authoring ~8x bigger stays sharp when the user enlarges it). Prints lint warnings."""
    for msg in svg_lint(svg_text):
        print("SVG WARNING:", msg)
    svg_text = _set_svg_size(svg_text, int(w * oversample), int(h * oversample))
    arc = "images/%s.svg" % re.sub(r"[^A-Za-z0-9_-]", "_", name)
    doc.extra_files[arc] = svg_text.encode("utf-8")
    return page.add({"image": {"id": uid(), "x": float(x), "y": float(y),
                               "width": float(w), "height": float(h),
                               "mime-type": "image/svg+xml", "source": arc,
                               "matrix": MATRIX}})

# ==========================================================================
# ---- olf_validate.py
# ==========================================================================

"""olf_validate.py -- run this on your .olf BEFORE delivering it. Standard library only.

    report = validate_olf("out.olf")        # path to .olf, or a content dict
    print_report(report)                    # prints ERRORS / WARNINGS / summary

Rule: fix every ERROR, re-run until `errors == []`, and show the user the final
report. WARNINGS are judgement calls; fix them unless you have a reason.

Every check here exists because of a real failure (see constraints/*.md).
"""
import json
import re
import textwrap
import zipfile

SEP = "\u300e\u300e\u300e"
META_KEYS = ["id", "create-platform", "create-by-library", "create-time", "modify-time",
             "create-library-version", "create-version", "modify-version", "modify-platform"]
SHAPE_KINDS = {"polygon", "ellipse", "polyline", "curve", "quadrant", "pseudo3Dshape"}
FLIP_KINDS = SHAPE_KINDS
HEX6, HEX8 = re.compile(r"^#[0-9A-Fa-f]{6}$"), re.compile(r"^#[0-9A-Fa-f]{8}$")
MATRIX9 = re.compile(r"^(-?[\d.eE+-]+,){8}-?[\d.eE+-]+$")


_PITCH = {"Segoe UI": 1.80, "Calibri": 1.65, "Georgia": 1.55, "Open Sans": 1.85,
          "Times New Roman": 1.55}      # measured pitch/pt rounded up; bold is NOT different


def _est_lines(text, pt, width, bold=False, avg=None):
    px = round(pt * 4 / 3)
    avg = avg or (0.60 if bold else 0.55)          # fraction of the pixel font size per character
    per = max(1, int(width / (px * avg)))
    return sum(max(1, len(textwrap.wrap(p, per, break_long_words=True)))
               for p in str(text).split("\n"))


def validate_olf(src):
    errs, warns = [], []
    E, Wn = errs.append, warns.append

    # ---- load -------------------------------------------------------------
    zipnames, svgs = None, {}
    if isinstance(src, dict):
        data = src
    else:
        try:
            with zipfile.ZipFile(src) as zf:
                names = zf.namelist()
                zipnames = set(names)
                if "content.json" not in names:
                    E("ZIP has no content.json at the archive ROOT (found: %s)" % names[:5])
                    return {"errors": errs, "warnings": warns, "stats": {}}
                data = json.loads(zf.read("content.json").decode("utf-8"))
                for nm in names:
                    if nm.lower().endswith(".svg"):
                        svgs[nm] = zf.read(nm).decode("utf-8", "replace")
        except zipfile.BadZipFile:
            E("not a valid ZIP file")
            return {"errors": errs, "warnings": warns, "stats": {}}

    # ---- envelope ---------------------------------------------------------
    if not isinstance(data, dict) or list(data.keys()) != ["olf"]:
        E("root must be an object with exactly one key 'olf' (got %s)"
          % (list(data.keys()) if isinstance(data, dict) else type(data).__name__))
        return {"errors": errs, "warnings": warns, "stats": {}}
    olf = data["olf"]
    for k in ("width", "height", "viewbox", "meta", "pageset", "additional", "links", "groups"):
        if k not in olf:
            E("olf missing key '%s'" % k)
    if " " not in str(olf.get("viewbox", "")) or "," in str(olf.get("viewbox", "")):
        E("olf.viewbox must be SPACE-separated, e.g. '0 0 1920 1080' (got %r)" % olf.get("viewbox"))
    for k in META_KEYS:
        if k not in olf.get("meta", {}):
            E("meta missing '%s' (all 9 fields required)" % k)
    if not isinstance(olf.get("additional"), list):
        E("'additional' must be ONE array on the root olf object")

    ids, elems = {}, {}              # id -> where ; element id -> (kind, dict, page_no)
    def reg(i, where):
        if not i:
            E("%s has no id" % where)
        elif i in ids:
            E("duplicate id %s (%s and %s)" % (i, ids[i], where))
        else:
            ids[i] = where

    reg(olf.get("meta", {}).get("id"), "meta")
    pages = olf.get("pageset", [])
    if not pages:
        E("pageset is empty")
    for pn, wrap in enumerate(pages, 1):
        if not isinstance(wrap, dict) or list(wrap.keys()) != ["page"]:
            E("pageset[%d] must be {\"page\": {...}}" % (pn - 1))
            continue
        pg = wrap["page"]
        reg(pg.get("id"), "page %d" % pn)
        if "," not in str(pg.get("viewbox", "")) or " " in str(pg.get("viewbox", "")):
            E("page %d viewbox must be COMMA-separated '0,0,1920,1080' (got %r)"
              % (pn, pg.get("viewbox")))
        if "matrix" not in pg:
            E("page %d missing 'matrix'" % pn)
        if "is-hidden" not in pg:
            E("page %d missing 'is-hidden'" % pn)
        bgs = pg.get("backgrounds")
        if not isinstance(bgs, list) or not bgs or "background" not in bgs[0]:
            E("page %d 'backgrounds' must be an array of {\"background\": {id,type,fill,opacity}}" % pn)
        else:
            reg(bgs[0]["background"].get("id"), "page %d background" % pn)
        if "additional" in pg:
            E("page %d has its own 'additional' -- it belongs ONCE on the root olf object" % pn)
        for el in pg.get("elements", []):
            if not isinstance(el, dict) or len(el) != 1:
                E("page %d has a malformed element wrapper" % pn)
                continue
            kind, body = next(iter(el.items()))
            where = "page %d %s" % (pn, kind)
            reg(body.get("id"), where)
            elems[body.get("id")] = (kind, body, pn)
            _check_element(kind, body, where, E, Wn, reg)

    # ---- additional <-> elements -----------------------------------------
    refd = set()
    for i, a in enumerate(olf.get("additional", [])):
        e = a.get("element") if isinstance(a, dict) else None
        if not e:
            E("additional[%d] must be {\"element\": {...}}" % i)
            continue
        reg(e.get("id"), "additional[%d]" % i)
        ref = e.get("ref")
        if ref not in elems:
            E("additional[%d] ref %s matches no element" % (i, ref))
            continue
        if ref in refd:
            E("two additional entries for element %s" % ref)
        refd.add(ref)
        kind = elems[ref][0]
        if kind == "AI-pen" and "flip" in e:
            E("additional entry for AI-pen must NOT have 'flip'")
        if kind in FLIP_KINDS and e.get("flip") != "none":
            E("additional entry for %s needs \"flip\": \"none\"" % kind)
        for an in e.get("animation-container", []):
            d = an.get("animation", {})
            reg(d.get("id"), "animation")
            if not isinstance(d.get("duration"), str) or d.get("duration") not in "0123" or not d.get("duration"):
                E("animation duration must be the STRING '0'..'3' (got %r)" % d.get("duration"))
            if d.get("type") not in ("fade-in", "fade-out"):
                E("animation type must be fade-in|fade-out (got %r)" % d.get("type"))
    for rid, (kind, body, pn) in elems.items():
        if kind in SHAPE_KINDS and rid not in refd:
            E("page %d %s %s has no entry in root 'additional'" % (pn, kind, rid))

    # ---- links ------------------------------------------------------------
    n_pages = len(pages)
    for i, lk in enumerate(olf.get("links", [])):
        d = lk.get("link", {}) if isinstance(lk, dict) else {}
        reg(d.get("id"), "link %d" % i)
        if d.get("ref") not in elems:
            E("link %d ref matches no element" % i)
        lt = d.get("link-type")
        if lt == "page":
            pid = d.get("page-id")
            if not (isinstance(pid, str) and pid.isdigit() and 1 <= int(pid) <= n_pages):
                E("link %d page-id must be a 1-based ORDINAL STRING within 1..%d (got %r)"
                  % (i, n_pages, pid))
        elif lt == "web" and not d.get("url"):
            E("link %d web link needs 'url'" % i)
        elif lt not in ("page", "web", "text", "tool", "file", "audio"):
            E("link %d unknown link-type %r" % (i, lt))

    # ---- text: tables, overlap, height -----------------------------------
    cell_text = set()
    for rid, (kind, b, pn) in elems.items():
        if kind == "table":
            _check_table(b, pn, elems, cell_text, E, Wn)
    boxes = []
    for rid, (kind, b, pn) in elems.items():
        if kind != "textarea":
            continue
        txt, pt = _text_of(b)
        if pt:
            fam, bold = _font_of(b)
            # minimum honest height: (n-1) wrapped-line pitches + one line box (~1.25 x pt).
            # The starter reserves more (n x pitch); this is the floor, to avoid false alarms
            # on single-line boxes sized by hand.
            pitch = _PITCH.get(fam, 1.85)
            n_hi = _est_lines(txt, pt, b["width"], bold)                 # generous count
            n_lo = _est_lines(txt, pt, b["width"], bold, 0.48 if not bold else 0.52)  # tight count
            need_hi = ((n_hi - 1) * pitch + 1.25) * pt
            need_lo = ((n_lo - 1) * pitch + 1.25) * pt
            if b["height"] < need_lo * 0.95:           # too short even on the optimistic count
                E("page %d textarea %r: height %.1f < estimated wrapped height %.1f "
                  "(lines*pitch). Do NOT use pitch alone as height." % (pn, txt[:40], b["height"], need_lo))
            elif b["height"] < need_hi * 0.95:         # only the generous count disagrees
                Wn("page %d textarea %r: height %.1f may be too short if the text wraps to %d lines "
                   "(needs ~%.0f)" % (pn, txt[:40], b["height"], n_hi, need_hi))
            _check_rtf(b, txt, pt, pn, E, Wn)
        if rid not in cell_text:
            boxes.append((pn, rid, b["x"], b["y"], b["x"] + b["width"], b["y"] + b["height"], txt))
    for i in range(len(boxes)):
        for j in range(i + 1, len(boxes)):
            a, c = boxes[i], boxes[j]
            if a[0] != c[0]:
                continue
            ox = min(a[4], c[4]) - max(a[2], c[2])
            oy = min(a[5], c[5]) - max(a[3], c[3])
            if ox > 1 and oy > 1:           # true 2-D overlap (x AND y)
                E("page %d text overlap: %r and %r overlap by %.0fx%.0f"
                  % (a[0], a[6][:30], c[6][:30], ox, oy))
    # images: source must exist in the zip; SVG sources get linted
    for rid, (kind, b, pn) in elems.items():
        if kind == "image" and zipnames is not None:
            s = b.get("source")
            if s not in zipnames:
                E("page %d image source %r is not in the ZIP (images must be stored at that path)" % (pn, s))
            elif s in svgs:
                _lint_svg(s, svgs[s], b.get("width"), pn, Wn)
            if b.get("mime-type") == "image/svg+xml" and s and not str(s).lower().endswith(".svg"):
                Wn("page %d image mime is svg+xml but source %r does not end in .svg" % (pn, s))
    # off-canvas
    for rid, (kind, b, pn) in elems.items():
        if kind in ("textarea", "image", "table") and \
                (b.get("x", 0) < -1 or b.get("y", 0) < -1 or
                 b.get("x", 0) + b.get("width", 0) > 1921 or b.get("y", 0) + b.get("height", 0) > 1081):
            Wn("page %d %s extends beyond the 1920x1080 canvas" % (pn, kind))

    # ---- layout collisions between text and shapes / arrows ---------------
    per_page = {}
    for rid, (kind, b, pn) in elems.items():              # insertion order = draw order
        per_page.setdefault(pn, []).append((kind, b, rid))
    for pn, items in per_page.items():
        for i, (kind, b, rid) in enumerate(items):
            if kind != "textarea" or rid in cell_text:
                continue
            tb = (b["x"], b["y"], b["x"] + b["width"], b["y"] + b["height"])
            area = max(1.0, (tb[2] - tb[0]) * (tb[3] - tb[1]))
            txt = _text_of(b)[0]
            for kind2, b2, rid2 in items[i + 1:]:          # shapes drawn AFTER the text cover it
                if kind2 not in ("polygon", "ellipse", "AI-pen", "quadrant"):
                    continue
                sb = _bbox(kind2, b2)
                if not sb or not _opaque(kind2, b2):
                    continue
                ox = min(tb[2], sb[2]) - max(tb[0], sb[0])
                oy = min(tb[3], sb[3]) - max(tb[1], sb[1])
                if ox <= 2 or oy <= 2:
                    continue
                if ox * oy >= 0.9 * area:
                    E("page %d text %r is hidden BEHIND a %s drawn after it -- add the shape first, "
                      "the text after (draw order = list order)" % (pn, txt[:30], kind2))
                elif ox * oy >= 0.3 * area:
                    Wn("page %d text %r is partly covered by a %s drawn after it (%.0f%% of the box)"
                       % (pn, txt[:30], kind2, 100.0 * ox * oy / area))
        for kind, b, rid in items:
            if kind not in ("curve", "polyline"):
                continue
            pts = _line_points(kind, b)
            for kind2, b2, rid2 in items:
                if kind2 != "textarea" or rid2 in cell_text:
                    continue
                x0, y0, x1, y1 = b2["x"] + 4, b2["y"] + 4, b2["x"] + b2["width"] - 4, b2["y"] + b2["height"] - 4
                inside = sum(1 for (px, py) in pts if x0 < px < x1 and y0 < py < y1)
                if inside >= 3:
                    Wn("page %d a %s passes through the text %r -- move the arrow or the text"
                       % (pn, kind, _text_of(b2)[0][:30]))

    stats = {"pages": n_pages, "elements": len(elems), "additional": len(olf.get("additional", [])),
             "links": len(olf.get("links", []))}
    return {"errors": errs, "warnings": warns, "stats": stats}


def _mat(b):
    try:
        m = [float(v) for v in str(b.get("matrix", "")).split(",")]
        return m[0], m[2], m[4], m[5]          # sx, tx, sy, ty
    except Exception:
        return 1.0, 0.0, 1.0, 0.0


def _bbox(kind, b):
    """Canvas-space bounding box (x0, y0, x1, y1) of a filled shape, or None."""
    try:
        if kind == "polygon":
            pts = [tuple(float(v) for v in p.split(",")) for p in b["points"].split()]
            return (min(p[0] for p in pts), min(p[1] for p in pts),
                    max(p[0] for p in pts), max(p[1] for p in pts))
        sx, tx, sy, ty = _mat(b)
        if kind == "ellipse":
            return (tx, ty, tx + b["rx"] * 2, ty + b["ry"] * 2)
        if kind == "AI-pen":
            p = b["foreground-objects-container"][0]["path"]
            return (tx, ty, tx + sx * p["width"], ty + sy * p["height"])
    except Exception:
        return None
    return None


def _opaque(kind, b):
    try:
        if kind == "AI-pen":
            return b["foreground-objects-container"][0]["path"].get("fill-opacity", 1.0) >= 0.5
        return float(b.get("fill-opacity", 1.0)) >= 0.5
    except Exception:
        return False


def _line_points(kind, b):
    """~12 canvas-space sample points along a curve (quadratic) or polyline."""
    try:
        if kind == "polyline":
            pts = [tuple(float(v) for v in p.split(",")) for p in b["points"].split()]
            out = []
            for (ax, ay), (cx, cy) in zip(pts, pts[1:]):
                out += [(ax + (cx - ax) * t / 8.0, ay + (cy - ay) * t / 8.0) for t in range(9)]
            return out
        s, v, e = [tuple(float(q) for q in b[k].split(",")) for k in ("start-point", "second-point", "end-point")]
        out = []
        for t in [i / 12.0 for i in range(13)]:
            u = 1 - t
            out.append((b["x"] + u * u * s[0] + 2 * u * t * v[0] + t * t * e[0],
                        b["y"] + u * u * s[1] + 2 * u * t * v[1] + t * t * e[1]))
        return out
    except Exception:
        return []


def _font_of(b):
    for p in b.get("text-blocks-container", []):
        for t in p.get("paragraph", {}).get("text-list-container", []):
            r = t.get("text", {})
            return r.get("font-family", "Segoe UI"), r.get("font-weight") == "bold"
    return "Segoe UI", False


def _text_of(b):
    runs, pt = [], None
    for p in b.get("text-blocks-container", []):
        for t in p.get("paragraph", {}).get("text-list-container", []):
            r = t.get("text", {})
            runs.append(r.get("text", ""))
            if pt is None and r.get("font-size"):
                pt = r["font-size"] * 3 / 4          # px -> pt
    return "".join(runs), pt


def _check_rtf(b, txt, pt, pn, E, Wn):
    rtf = b.get("custom-data", "")
    if not rtf:
        Wn("page %d textarea %r has empty custom-data (RTF); Windows renders from RTF" % (pn, txt[:30]))
        return
    m = re.search(r"\\fs(\d+)", rtf)
    if m and abs(int(m.group(1)) - pt * 2) > 2:
        E("page %d textarea %r: RTF \\fs%s disagrees with JSON font-size (%.0f px => \\fs%.0f). "
          "JSON is px = pt*4/3; RTF is pt*2." % (pn, txt[:30], m.group(1), pt * 4 / 3, pt * 2))
    if "Arial" in rtf:
        Wn("page %d textarea %r: the literal word 'Arial' is rewritten to 'Calibri' by "
           "myViewBoard (escape it as Ari\\u8288?al; never use Arial as a font)" % (pn, txt[:30]))
    cm = re.search(r"\\red(\d+)\\green(\d+)\\blue(\d+)", rtf)
    for p in b.get("text-blocks-container", []):
        for t in p.get("paragraph", {}).get("text-list-container", []):
            f = t.get("text", {}).get("fill", "")
            if not HEX8.match(f):
                E("page %d textarea %r: text fill %r must be 8-digit #AARRGGBB" % (pn, txt[:30], f))
            elif cm:
                want = "#%02X%02X%02X" % tuple(int(v) for v in cm.groups())
                if f[3:].upper() != want[1:]:
                    E("page %d textarea %r: JSON fill %s != RTF colortbl %s" % (pn, txt[:30], f, want))


def _check_element(kind, b, where, E, Wn, reg):
    if "matrix" in b and not MATRIX9.match(str(b["matrix"])):
        E("%s matrix must be 9 comma-separated numbers (got %r)" % (where, b["matrix"]))
    if kind in ("polygon", "ellipse", "polyline", "curve", "quadrant", "pseudo3Dshape"):
        for key in ("fill", "stroke"):
            if key in b and not HEX6.match(str(b[key])):
                E("%s %s %r must be 6-digit #RRGGBB (8-digit is for TEXT fill only)" % (where, key, b[key]))
        if kind in ("curve", "polyline", "polygon", "ellipse") and "stroke-opacity" not in b:
            E("%s needs explicit stroke-opacity (a curve without it is INVISIBLE)" % where)
        if kind == "curve" and b.get("stroke-opacity", 1) == 0:
            E("%s stroke-opacity is 0 -- invisible arrow" % where)
        for key in ("show-length-measurement", "show-angle-measurement"):
            v = b.get(key)
            if v and ("\u300e" in v) and ("\u300e" * 3 not in v or "\u300e" * 4 in v):
                E("%s %s must use the TRIPLE separator (3 x U+300E), never 2 or 4" % (where, key))
            if v and "\u300e" not in v and "true" in v and v.count("true") > 1:
                E("%s %s has several entries but no U+300E separator" % (where, key))
    if kind == "textarea":
        for k in ("custom-data-tag", "text-blocks-container"):
            if k not in b:
                E("%s missing %s" % (where, k))
        if b.get("custom-data-tag") and b["custom-data-tag"] != "RTFxamlStr_UWP":
            Wn("%s custom-data-tag is %r (expected RTFxamlStr_UWP)" % (where, b["custom-data-tag"]))
        for p in b.get("text-blocks-container", []):
            pp = p.get("paragraph", {})
            reg(pp.get("id"), where + " paragraph")
            for t in pp.get("text-list-container", []):
                r = t.get("text", {})
                reg(r.get("id"), where + " run")
                fs = r.get("font-size")
                if fs is not None and fs > 130 * 4 / 3 + 1:
                    E("%s font-size %s px exceeds the 130pt cap" % (where, fs))
                if fs is not None and fs != int(fs):
                    Wn("%s font-size %s is not a whole pixel number" % (where, fs))
    if kind == "image" and not b.get("source"):
        E("%s image missing 'source'" % where)
    if kind == "AI-pen":
        _check_ai_pen(b, where, E, Wn, reg)


_IDENT = "1,0,0,0,1,0,0,0,1"
_BAD_SVG = [("<pattern", "<pattern> fills render SOLID BLACK"), ("<mask", "<mask> is ignored"),
            ("<text", "<text> renders NOTHING (convert to paths)"),
            ("<use", "<use> does not resolve (inline it)"), ("<symbol", "<symbol> does not resolve"),
            ("<foreignObject", "<foreignObject> content is dropped"),
            ("<animate", "SMIL animation never plays"), ("<set ", "SMIL animation never plays"),
            ("@keyframes", "CSS animation never plays")]


def _lint_svg(name, text, display_w, pn, Wn):
    for tok, msg in _BAD_SVG:
        if tok in text:
            Wn("page %d SVG %s: %s" % (pn, name, msg))
    m = re.search(r"<svg\b[^>]*>", text)
    if m and display_w:
        wm = re.search(r'\bwidth="([\d.]+)', m.group(0))
        if not wm:
            Wn("page %d SVG %s has no width attribute -- intrinsic size unknown; author ~8x display" % (pn, name))
        elif float(wm.group(1)) < display_w * 4:
            Wn("page %d SVG %s intrinsic width %s < 4x display %.0f -- will look blurry" % (pn, name, wm.group(1), display_w))


def _check_ai_pen(b, where, E, Wn, reg):
    fgs = b.get("foreground-objects-container", [])
    bgs = b.get("background-objects-container", [])
    if not fgs:
        E("%s has no foreground-objects-container paths" % where)
    if not bgs:
        E("%s background-objects-container is EMPTY -- must mirror the foreground at fill-opacity 0.3 "
          "or the shape can render invisible" % where)
    elif len(bgs) != len(fgs):
        Wn("%s background has %d paths, foreground %d (should mirror)" % (where, len(bgs), len(fgs)))
    if b.get("matrix") == _IDENT:
        E("%s uses the IDENTITY matrix -- AI-pen needs a real scale/translate matrix or it can render invisible" % where)
    for grp, lst in (("foreground", fgs), ("background", bgs)):
        for item in lst:
            pth = item.get("path", {})
            reg(pth.get("id"), where + " " + grp + " path")
            for key in ("fill", "stroke"):
                if not HEX6.match(str(pth.get(key, ""))):
                    E("%s %s path %s %r must be plain #RRGGBB (non-hex CRASHES Android)"
                      % (where, grp, key, pth.get(key)))
            d = str(pth.get("data", ""))
            if not d:
                E("%s %s path has no 'data'" % (where, grp))
                continue
            if grp == "foreground":
                if re.search(r"[HhVvQqTtSsmlcaz]", d):
                    Wn("%s path data uses relative/shorthand commands (H V Q S T or lowercase) -- "
                       "prefer absolute M L C A Z only" % where)
                if re.search(r"(?<![0-9.eE])-\d", d):
                    Wn("%s path data has NEGATIVE coordinates -- keep local coords >= 0 and fold the "
                       "offset into the matrix" % where)
            if "url(" in d or "currentColor" in d:
                E("%s path data contains a paint reference" % where)


def _check_table(b, pn, elems, cell_text, E, Wn):
    rows, cols = b.get("rows", 0), b.get("columns", 0)
    nb = len(b.get("cell-background-container", []))
    if nb != rows * cols:
        E("page %d table: cell-background-container has %d entries, expected rows*cols=%d" % (pn, nb, rows * cols))
    mc = b.get("merge-cell-container", [])
    if mc and len(mc) != rows * cols:
        E("page %d table: merge-cell-container must have one entry per cell (%d), has %d" % (pn, rows * cols, len(mc)))
    for c in b.get("cell-content-container", []):
        d = c.get("cell-content", {})
        r, k = d.get("cell-row"), d.get("cell-column")
        if r is None or k is None or r % 2 or k % 2 or r > 2 * (rows - 1) or k > 2 * (cols - 1):
            E("page %d table cell-content (%s,%s) must use EVEN indices 2r,2c within the table" % (pn, r, k))
        if d.get("ref") not in elems:
            E("page %d table cell-content ref matches no element" % pn)
        else:
            cell_text.add(d["ref"])
    for lst in ("column-lengths-array", "row-lengths-array"):
        n = len(str(b.get(lst, "")).split())
        if n != (cols if lst.startswith("column") else rows):
            E("page %d table %s has %d values, expected %d" % (pn, lst, n, cols if lst.startswith("column") else rows))


def print_report(rep):
    print("STATS:", rep["stats"])
    for e in rep["errors"]:
        print("ERROR  :", e)
    for w in rep["warnings"]:
        print("WARNING:", w)
    print("RESULT : %s (%d errors, %d warnings)" % (
        "PASS" if not rep["errors"] else "FAIL", len(rep["errors"]), len(rep["warnings"])))
    return not rep["errors"]


if __name__ == "__main__":
    import sys
    # Only acts when run as a CLI with a path; harmless when pasted into a sandbox.
    if len(sys.argv) > 1 and sys.argv[1].lower().endswith(".olf"):
        sys.exit(0 if print_report(validate_olf(sys.argv[1])) else 1)
